Migrating application to JPMS. common, user, product and checkout modules are now "JPMS-modularized" but not the app module.
When module-info.java was added to the app module:
module natay.bakery.app {
    requires natay.bakery.common;
    requires natay.bakery.user;
    requires natay.bakery.product;
    requires natay.bakery.checkout;

    requires java.validation;
    requires spring.context;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.web;
    requires spring.security.core;
    requires spring.security.web;
    requires jasypt.spring.boot;
    requires org.apache.tomcat.embed.core;
    requires org.slf4j;
    requires lombok;
}

it was fine running the application via the maven spring boot plugin:
mvn spring-boot:run -Dspring-boot.run.profiles=test
However, tests in the app module would fail with error:
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test